### ISSUE TITLE
controller crashes

### ISSUE THREAD

**Issue by malikumaliku** [kubernetes-csi/csi-driver-nfs#235]
In my test setup the controller pod is restarting.
The application layer using the PersistenVolume returns IO errors, 
I assume that the crashes in the controller is what makes errors on the application.
Confirmed using kubernetes 1.21.5 and Calico 3.20.1 , 3.20.2

The csi nfs controller "csi-provisioner"  logs gives the following output of the run before the restart

I have tried with several NFS mount options and exports... and there is no improvement on the crashes.
NFS 3 or 4.1 , hard vs soft,  sync vs async... all of them end up in this situation.

Logs of the previous runs
```
k8s.io/apimachinery/pkg/util/wait.Until(0xc00037d8a0, 0x3b9aca00, 0xc0004040c0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:881 +0x3d6
goroutine 343 [sync.Cond.Wait, 112 minutes]:
sync.runtime_notifyListWait(0xc0000f46d0, 0x55)
/usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc0000f46c0)
/usr/local/go/src/sync/cond.go:56 +0x99
k8s.io/client-go/util/workqueue.(*Type).Get(0xc0002eade0, 0x0, 0x0, 0x0)
/workspace/vendor/k8s.io/client-go/util/workqueue/queue.go:151 +0x89
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).processNextClaimWorkItem(0xc000252a00, 0x1e18f50, 0xc00003a100, 0x203000)
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:935 +0x3e
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).runClaimWorker(...)
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:924
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1.2()
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:880 +0x5c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00037d8c0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00037d8c0, 0x1de1ea0, 0xc00036ed20, 0x1, 0xc0004040c0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00037d8c0, 0x3b9aca00, 0x0, 0x1, 0xc0004040c0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00037d8c0, 0x3b9aca00, 0xc0004040c0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:880 +0x4af
goroutine 344 [sync.Cond.Wait, 112 minutes]:
sync.runtime_notifyListWait(0xc0000f4c10, 0x56)
/usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc0000f4c00)
/usr/local/go/src/sync/cond.go:56 +0x99
k8s.io/client-go/util/workqueue.(*Type).Get(0xc0002eafc0, 0x0, 0x0, 0x0)
/workspace/vendor/k8s.io/client-go/util/workqueue/queue.go:151 +0x89
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).processNextVolumeWorkItem(0xc000252a00, 0x1e18f50, 0xc00003a100, 0x203000)
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:990 +0x3e
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).runVolumeWorker(...)
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:929
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1.3()
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:881 +0x5c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00037d8e0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00037d8e0, 0x1de1ea0, 0xc00036ed50, 0x1, 0xc0004040c0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00037d8e0, 0x3b9aca00, 0x0, 0x1, 0xc0004040c0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00037d8e0, 0x3b9aca00, 0xc0004040c0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:881 +0x3d6
goroutine 345 [sync.Cond.Wait, 112 minutes]:
sync.runtime_notifyListWait(0xc0000f46d0, 0x58)
/usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc0000f46c0)
/usr/local/go/src/sync/cond.go:56 +0x99
k8s.io/client-go/util/workqueue.(*Type).Get(0xc0002eade0, 0x0, 0x0, 0x0)
/workspace/vendor/k8s.io/client-go/util/workqueue/queue.go:151 +0x89
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).processNextClaimWorkItem(0xc000252a00, 0x1e18f50, 0xc00003a100, 0x203000)
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:935 +0x3e
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).runClaimWorker(...)
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:924
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1.2()
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:880 +0x5c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00037d900)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00037d900, 0x1de1ea0, 0xc00036ed80, 0x1, 0xc0004040c0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00037d900, 0x3b9aca00, 0x0, 0x1, 0xc0004040c0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00037d900, 0x3b9aca00, 0xc0004040c0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:880 +0x4af
goroutine 346 [sync.Cond.Wait, 82 minutes]:
sync.runtime_notifyListWait(0xc0000f4c10, 0x76)
/usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc0000f4c00)
/usr/local/go/src/sync/cond.go:56 +0x99
k8s.io/client-go/util/workqueue.(*Type).Get(0xc0002eafc0, 0x0, 0x0, 0x0)
/workspace/vendor/k8s.io/client-go/util/workqueue/queue.go:151 +0x89
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).processNextVolumeWorkItem(0xc000252a00, 0x1e18f50, 0xc00003a100, 0x203001)
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:990 +0x3e
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).runVolumeWorker(...)
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:929
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1.3()
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:881 +0x5c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00037d920)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00037d920, 0x1de1ea0, 0xc00036e7b0, 0x1, 0xc0004040c0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00037d920, 0x3b9aca00, 0x0, 0x1, 0xc0004040c0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00037d920, 0x3b9aca00, 0xc0004040c0)
/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1
/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:881 +0x3d6
```

Logs of the run after restarts
```
I1009 11:22:03.141765 1 feature_gate.go:243] feature gates: &{map[]}
I1009 11:22:03.141843 1 csi-provisioner.go:138] Version: v2.2.2
I1009 11:22:03.141870 1 csi-provisioner.go:161] Building kube configs for running in cluster...
I1009 11:22:03.244006 1 common.go:111] Probing CSI driver for readiness
I1009 11:22:03.335746 1 csi-provisioner.go:212] Detected CSI driver nfs.csi.k8s.io
I1009 11:22:03.336887 1 csi-provisioner.go:284] CSI driver does not support PUBLISH_UNPUBLISH_VOLUME, not watching VolumeAttachments
I1009 11:22:03.337334 1 controller.go:756] Using saving PVs to API server in background
I1009 11:22:03.338258 1 leaderelection.go:243] attempting to acquire leader lease csi-driver-nfs/nfs-csi-k8s-io...
I1009 11:22:03.344501 1 leaderelection.go:253] successfully acquired lease csi-driver-nfs/nfs-csi-k8s-io
I1009 11:22:03.344653 1 leader_election.go:205] became leader, starting
I1009 11:22:03.344787 1 reflector.go:219] Starting reflector *v1.StorageClass (1h0m0s) from k8s.io/client-go/informers/factory.go:134
I1009 11:22:03.344877 1 reflector.go:219] Starting reflector *v1.PersistentVolumeClaim (15m0s) from k8s.io/client-go/informers/factory.go:134
I1009 11:22:03.533659 1 controller.go:835] Starting provisioner controller nfs.csi.k8s.io_ubuntu2004.localdomain_4ba57dc0-b6da-41db-8471-7cf6d5401e66!
I1009 11:22:03.533748 1 volume_store.go:97] Starting save volume queue
I1009 11:22:03.533940 1 reflector.go:219] Starting reflector *v1.PersistentVolume (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:869
I1009 11:22:03.533945 1 reflector.go:219] Starting reflector *v1.StorageClass (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:872
I1009 11:22:03.634109 1 controller.go:884] Started provisioner controller nfs.csi.k8s.io_ubuntu2004.localdomain_4ba57dc0-b6da-41db-8471-7cf6d5401e66!
E1009 11:29:34.194350 1 leaderelection.go:361] Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io "nfs-csi-k8s-io": the object has been modified; please apply your changes to the latest version and try again
E1009 11:29:49.240744 1 leaderelection.go:361] Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io "nfs-csi-k8s-io": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by andyzhangx** [comment]
more details? is this panic related to this project?

**Comment by malikumaliku** [comment]
Ticket is being updated

**Comment by malikumaliku** [comment]
4 PV, 
With csi-smb I confirm that there are no IO errors.
With NFS 3 and option no locks, seems also ok
With NFS 4.0 and NFS 4.1 errors (with and without locks)

csi-nfs does not work on NFS 3 without deactivating server side locks option.

**Comment by andyzhangx** [comment]
could you get the `nfs` container logs, I think it should panic in nfs container
